spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: user
    password: 123
#    data: classpath:data.sql
#    initialization-mode: always

  jpa:
    defer-datasource-initialization: true # ddl 후 script 실행
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: create

    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
    #        format_sql: 'true'