spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/mileage
    username: sa
    password: 123

  jpa:
#    show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create

    properties:
      dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: true
    #        format_sql: 'true'

logging:
  level:
    org:
      #      hibernate: info
#      SQL: debug